name: 'Get & Cache Dependencies'
description: 'Get & Cache Dependencies (via npm) for faster builds'
inputs:
  cache-key-prefix:
    description: 'Prefix for cache key (default: deps-node-modules)'
    required: false
    default: 'deps-node-modules'
  fail-on-cache-miss:
    description: 'Fail the job if cache is not found'
    required: false
    default: 'false'
  enable-cross-os-archive:
    description: 'Enable cross-OS caching (allows sharing cache across different OS)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: 'Restore Dependencies Cache'
      uses: 'actions/cache/restore@v4'
      id: cache-node-modules
      with:
        path: |
          node_modules
          ~/.npm
        key: ${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-
          ${{ inputs.cache-key-prefix }}-
        fail-on-cache-miss: ${{ inputs.fail-on-cache-miss }}
        enableCrossOsArchive: ${{ inputs.enable-cross-os-archive }}

    - name: 'Install Dependencies'
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash

    - name: 'Save Dependencies Cache'
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      uses: 'actions/cache/save@v4'
      with:
        path: |
          node_modules
          ~/.npm
        key: ${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        enableCrossOsArchive: ${{ inputs.enable-cross-os-archive }}
