name: 'Get & Cache Dependencies'
description: 'Get & Cache Dependencies (via npm) for faster builds'
inputs:
  cache-key-prefix:
    description: 'Prefix for cache key (default: deps-node-modules)'
    required: false
    default: 'deps-node-modules'
  fail-on-cache-miss:
    description: 'Fail the job if cache is not found'
    required: false
    default: 'false'
  enable-cross-os-archive:
    description: 'Enable cross-OS caching (allows sharing cache across different OS)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: 'Restore Dependencies Cache'
      uses: 'actions/cache/restore@v4'
      id: cache-node-modules
      with:
        path: |
          node_modules
          ~/.npm
        key: ${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-
          ${{ inputs.cache-key-prefix }}-
        fail-on-cache-miss: ${{ inputs.fail-on-cache-miss }}
        enableCrossOsArchive: ${{ inputs.enable-cross-os-archive }}

    - name: 'Debug Info'
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        echo "=== Environment Debug Info ==="
        echo "Node version: $(node --version)"
        echo "npm version: $(npm --version)"
        echo "OS: $(uname -a)"
        echo "Disk space:"
        df -h | head -5
        echo "Working directory: $(pwd)"
        echo "Package files:"
        ls -lh package*.json 2>/dev/null || echo "No package files found"
        echo "package-lock.json size:"
        ls -lh package-lock.json 2>/dev/null || echo "package-lock.json not found"
        echo "Workspace directories:"
        ls -d apps/* libs/* 2>/dev/null | head -10 || echo "No workspace dirs found"
        echo "=============================="
      shell: bash

    - name: 'Install Dependencies'
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        echo "=== Starting npm ci installation ==="
        echo "Start time: $(date -u +%Y-%m-%dT%H:%M:%SZ)"

        # Show npm configuration for debugging
        echo "npm config:"
        npm config list || true

        # Run npm ci with progress and verbose logging
        npm ci --loglevel=info --no-audit --no-fund || {
          EXIT_CODE=$?
          echo "npm ci failed with exit code: $EXIT_CODE"
          echo "End time: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          exit $EXIT_CODE
        }

        echo "=== npm ci completed successfully ==="
        echo "End time: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
      shell: bash

    - name: 'Save Dependencies Cache'
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      uses: 'actions/cache/save@v4'
      with:
        path: |
          node_modules
          ~/.npm
        key: ${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        enableCrossOsArchive: ${{ inputs.enable-cross-os-archive }}
